server:
  port: 8080

spring:
  application:
    name: sharding-jdbc-learn
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    props:
      sql:
        show: true
    datasource:
      names: ds1
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/sharding-learn-master?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
        username: root
        password: password
        maxPoolSize: 100
        minPoolSize: 5
      ds2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/sharding-learn-slave?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
        username: root
        password: password
        maxPoolSize: 100
        minPoolSize: 5
    sharding:
      default-data-source-name: ds1
      tables:
        user:
          actual-data-nodes: ds1.user_$->{0..1}
          table-strategy:
#            standard:
#              sharding-column: age
#              precise-algorithm-class-name: com.example.config.StandardStrategy
            hint:
              algorithm-class-name: com.example.config.TableHint


